### ISSUE TITLE
None of the methods of rcu_list or rcu_guarded are documented

### ISSUE THREAD

**Issue by Bu11etmagnet** [copperspice/libguarded#10]
https://www.copperspice.com/docs/libguarded/classlibguarded_1_1rcu__guarded.html and 
https://www.copperspice.com/docs/libguarded/classlibguarded_1_1rcu__list.html

are devoid of any public member documentation.

Is this intentional?

**Comment by agserm** [comment]
Thank you for your interest in libGuarded. Some of our classes and methods have been documented, others have not. If you would like to contribute to the documentation we would be very happy to incorporate any submissions.

For more information on how libGuarded works, you may want to refer to the video from CppNow in May 2017. This is available from our main presentation page: https://www.copperspice.com/presentations.html
