### ISSUE TITLE
deleters not move_assignable

### ISSUE THREAD

**Issue by phlptp** [copperspice/libguarded#8]
I ran into a situation where I needed to be able to unlock a shared_guarded object for a short time while a callback was called.

the callback could in principle call other functions that would trigger the same lock, so I couldn't have the lock be engaged while the callback was executing.  

But this was executing in a loop so the lock needed to reengaged after the callback finished.  
an unlock() function on the handle would be really nice but that would require the handle be a full class instead of a unique_ptr, so I settled for setting the handle to nullptr then calling lock again.  

This generated a compile error as the use of M & m_deleter_mutex; is not move assignable,  thus the deleter class itself is not move_assignable and the handle is not move_assignable, and there was no way to have a lock reassigned to an existing variable.

My solution was to change the deleter class to store M * instead of M & and change the unlock call to use -> instead of . and the constructor to store &mutex instead.  This allowed the handle to be move_assignable and at least some work around to temporary unlocking.  

The same issue would be true for guarded and ordered_guarded and probably others as well.
this 
the cost of course is that now deleter  has a pointer instead of a reference and could not be zero size,  but there had to be some mechanism for temporary disengaging the lock otherwise the guarded classes are unusable for a number of purposes.  

There are a variety of other alternatives, but the issue is that there is no means of temporarily suspending a lock in a conditional branch.

**Comment by agserm** [comment]
Thanks for this report. I finally realized that using the `std::shared_lock` functionality in the same way that the `guarded` class uses `std::unique_lock` would allow this use case and remove the requirement for the reference. The updated code is committed in 36ad306. Can you test and verify that this solves your issue?

**Comment by janwilmans** [comment]
Looks good, we solving lots of problems

**Comment by agserm** [comment]
Closing due to lack of response. Feel free to open a new ticket if this issue still exists in your use case.

**Comment by phlptp** [comment]
I had forgotten this was open.  We moved to using a handle based object from the return of lock() that could be used.  We also had need for a couple other types of locks, so all that is in https://github.com/GMLC-TDC/concurrency  Many of which are based on libguarded, but are modified quite a bit to work a little cleaner in our use cases.    This issue is what spurred a lot of the development for the handles design
