### ISSUE TITLE
guarded::deleter doesn't compile with -Wall -Wextra

### ISSUE THREAD

**Issue by kaa-ching** [copperspice/libguarded#9]
See method `guarded::deleter::operator(T* ptr)`, line 113. The `ptr` argument variable is not referenced. This causes warnings when compiled with -Wall -Wextra.

**Comment by agserm** [comment]
Thank you for your report. This issue should be resolved by 2b9d8ff.

**Comment by janwilmans** [comment]
Glad to be of service, klaas ;)
